steps:
    - name: 'gcr.io/cloud-builders/git'
      args: ['clone', 'https://github.com/dsGCloud/shop-at-anthos.git']
      # Install npm dependencies
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install', '--save', 'prpl-server']
      # npm audit
    - name: "gcr.io/cloud-builders/npm"
      args: ['audit', 'fix']
      # Build polymer application
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
      # Build Docker container
    - name: gcr.io/cloud-builders/docker
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/shop-at-anthos:$REVISION_ID', './']
      # Push container to gcr.io repo
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/$PROJECT_ID/shop-at-anthos"]
      # Deploy container image to Cloud Run in GKE
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'shop-at-anthos', '--image', 'gcr.io/$PROJECT_ID/shop-at-anthos:$REVISION_ID', '--platform', 'gke', '--cluster', 'dev-platzi', '--cluster-location', 'us-central1-a']
  